### ISSUE TITLE
After adding tasks, calendar shows up all tasks by sorting their priority

### ISSUE THREAD

**Issue by elaina-liu** [xlab-classes/cse442-spring2022-team-niubility-1#18]

**Comment by elaina-liu** [comment]
Task test:
1: Open the website.
2: Enter the user name and password and log in.
3: Go to the calendar page, add some tasks with different priorities to the calendar
4: Go back to the calendar page
5: Check if tasks are organized by their priority.

**Comment by AnthonyIreo** [comment]
Test1 to check priority:
1: Open the web page and log in.

2: In homepage, click the 'add task' button.

3: Enter the task name 'high' and set the priority to '1'

4: Confirm the task.

5: In the homepage, click the 'add task' button to create another task.

6: Enter the task name 'low' and set the priority to '2'

7: Confirm the task.

8: Back to the homepage and the 'high' will be arranged in first and 'low' in second.
