### ISSUE TITLE
Make sure tasks appear to only the users that put them on the calendar instead of appearing to all users

### ISSUE THREAD

**Issue by AnthonyIreo** [xlab-classes/cse442-spring2022-team-niubility-1#25]

**Comment by mzhao092021** [comment]
Test:

1: Open the browser, go to the website (link should be provided from the course webserver), and log in with your information. 

2: Click the 'add tasks' button and add tasks.

3: Click 'Log out' and switch an account log in again. 

4: Test passes, if the homepage didn't show tasks of the previous account.
