### ISSUE TITLE
As a user, I don't want to work on weekends in the Scheduling, so I can choose to not work on weekends.

### ISSUE THREAD

**Issue by huangwenhui117** [xlab-classes/cse442-spring2022-team-niubility-1#4]
Acceptance Test:

1. user check the box of "not work on weekend"
2. click "save"
3. show a schedule that is any task on weekend.

**Comment by elaina-liu** [comment]
Acceptance task for putting finished tasks back to calendar
1: Open the website.
2: Enter the user name and password.
3: Click the login button.
4: Go to the calendar page, click the addTask button
5: automatically lead you to the addTask page
6: Click unwanted time period and choose task type to be unwanted
7: Click confirm button 
8: Click the add button to add some wanted tasks to your calendar
9: Click the confirm button
10: Click the Calendar button
11: Automatically go back to the calendar page 
12: Check if tasks are not assigned to unwanted period
