### ISSUE TITLE
As a user, I want to put back my unfinished tasks to my schedule, so that I can continue doing my tasks.

### ISSUE THREAD

**Issue by huangwenhui117** [xlab-classes/cse442-spring2022-team-niubility-1#5]

**Comment by elaina-liu** [comment]
Acceptance task for putting finished tasks back to calendar
1: Open the website.
2: Enter the user name and password.
3: Click the login button.
4: Go to the calendar page, click the history button 
5: Click the task that you want to put back
6: Click the confirm button to confirm putting back the task
7: Click the calendar button to return to the calendar page
8: Check if the task has been added back to calendar
