### ISSUE TITLE
As a manager, I want to be able to organize my tasks. So I can arrange my tasks by priority and deadline. 

### ISSUE THREAD

**Issue by huangwenhui117** [xlab-classes/cse442-spring2022-team-niubility-1#7]
Test:

1. user inputs all the tasks, and inputs all the info of all the tasks
2. click "schedule"
3. show a schedule that arranges tasks by priority and deadline.

 Test passes if all tasks are arranges by priority and deadline.

**Comment by AnthonyIreo** [comment]
Test1 to arrange tasks:
1: Open the web page and log in to the homepage.

2: Click the 'add task' and enter the name 'breakfast'.

3: Set the deadline in one hour, priority in '1' and color in red.

4: Click confirm button.

5: Back to the homepage and select the task 'breakfast'.

6: Click the 'edit' button, change the deadline to the next day and priority to '3'.

7: Click confirm and back to homepage.

8: The task 'breakfast' 's deadline and priority has changed.
